# Generated by Django 6.0.3 on 2026-04-10 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_fulfillment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('postcode', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='GB', max_length=2)),
                ('payment_terms', models.CharField(choices=[('cod', 'Cash on Delivery'), ('net_7', 'Net 7 days'), ('net_14', 'Net 14 days'), ('net_30', 'Net 30 days'), ('net_60', 'Net 60 days'), ('net_90', 'Net 90 days')], default='net_30', max_length=10)),
                ('is_dropshipper', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_sku', models.CharField(blank=True, default='', max_length=100)),
                ('supplier_url', models.URLField(blank=True, default='', max_length=500)),
                ('last_cost', models.PositiveIntegerField(default=0, help_text='Last purchase cost in pence (net of VAT)')),
                ('last_purchased_at', models.DateTimeField(blank=True, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['variant', 'is_preferred'], name='suppliers_s_variant_5c1de7_idx')],
                'unique_together': {('supplier', 'variant')},
            },
        ),
    ]
