# Generated by Django 6.0.3 on 2026-04-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fulfillment_type',
            field=models.CharField(choices=[('self', 'Self-fulfilled'), ('dropship', 'Dropship')], db_index=True, default='self', max_length=10),
        ),
    ]
