# Generated by Django 6.0.3 on 2026-06-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_fit_notes_product_size_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='manual_unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
