# Generated by Django 6.0.3 on 2026-04-10 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.PositiveIntegerField(help_text='Net of VAT, in pence')),
                ('vat_amount', models.PositiveIntegerField(default=0)),
                ('line_total', models.PositiveIntegerField(default=0, help_text='Gross including VAT')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('unit_cost', models.PositiveIntegerField(help_text='Cost per unit in pence (net of VAT)')),
                ('received_at', models.DateTimeField(db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['received_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('purchase_received', 'Purchase received'), ('sale', 'Sale'), ('return', 'Customer return'), ('adjustment', 'Manual adjustment'), ('dropship_fulfilled', 'Dropship fulfilled'), ('refund_restock', 'Refund restock')], db_index=True, max_length=30)),
                ('quantity', models.IntegerField(help_text='Positive = increase, negative = decrease')),
                ('unit_cost_at_time', models.PositiveIntegerField(default=0)),
                ('total_cost', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(db_index=True, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to supplier'), ('partial', 'Partially received'), ('received', 'Fully received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('vat_amount', models.PositiveIntegerField(default=0)),
                ('shipping_cost', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
