# Generated by Django 6.0.3 on 2026-04-10 21:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_discount_amount_order_promotion_code_and_more'),
        ('products', '0002_product_fulfillment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField()),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='Admin can hide a review without deleting it.')),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('admin_reply', models.TextField(blank=True, default='')),
                ('admin_reply_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reply_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_replies', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='The order that proves verified-buyer status at write time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_helpful_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_visible', '-created_at'], name='reviews_rev_product_a96940_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_visible', '-rating'], name='reviews_rev_product_c30c51_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_visible', '-helpful_count'], name='reviews_rev_product_a2d2aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='uniq_review_per_product_per_user'),
        ),
        migrations.AddConstraint(
            model_name='reviewhelpfulvote',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='uniq_helpful_vote_per_user'),
        ),
    ]
