# Generated by Django 6.0.3 on 2026-06-02 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_customization_surcharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_threshold_pence', models.PositiveIntegerField(default=3000, help_text='Subtotal at or above which shipping is free. In pence.')),
                ('flat_rate_pence', models.PositiveIntegerField(default=399, help_text='Shipping charged when subtotal is below the free threshold. In pence.')),
            ],
            options={
                'verbose_name': 'Shipping settings',
                'verbose_name_plural': 'Shipping settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
