# Generated by Django 6.0.3 on 2026-04-10 22:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('events', models.PositiveIntegerField(default=0)),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('revenue_pence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_hash', models.CharField(db_index=True, max_length=64)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('other', 'Other')], default='other', max_length=20)),
                ('browser', models.CharField(blank=True, default='', max_length=40)),
                ('os', models.CharField(blank=True, default='', max_length=40)),
                ('pageview_count', models.PositiveIntegerField(default=0)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('last_activity_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('entry_path', models.CharField(blank=True, default='', max_length=500)),
                ('exit_path', models.CharField(blank=True, default='', max_length=500)),
                ('referrer', models.URLField(blank=True, default='', max_length=500)),
                ('referrer_host', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('utm_source', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('utm_content', models.CharField(blank=True, default='', max_length=100)),
                ('pageview_count', models.PositiveIntegerField(default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('viewed_at', models.DateTimeField(db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='analytics.session')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.session')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['last_seen_at'], name='analytics_v_last_se_da2848_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['country'], name='analytics_v_country_361d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['device_type'], name='analytics_v_device__dfd0cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='visitor',
            constraint=models.UniqueConstraint(fields=('daily_hash', 'user'), name='uniq_visitor_per_day_per_user'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['visitor', '-started_at'], name='analytics_s_visitor_b42988_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['utm_source'], name='analytics_s_utm_sou_8e7d80_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['path', 'viewed_at'], name='analytics_p_path_06b4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['visitor', '-viewed_at'], name='analytics_p_visitor_6710e9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name', 'occurred_at'], name='analytics_e_name_a15d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visitor', '-occurred_at'], name='analytics_e_visitor_f56888_idx'),
        ),
    ]
