# Generated by Django 6.0.3 on 2026-04-06 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Select'), ('multi_select', 'Multi-Select')], default='text', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('is_filterable', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='attributes.attribute')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='attributes.attribute')),
            ],
            options={
                'unique_together': {('attribute', 'language')},
            },
        ),
        migrations.CreateModel(
            name='AttributeValueTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('value', models.CharField(max_length=300)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='attributes.attributevalue')),
            ],
            options={
                'unique_together': {('attribute_value', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('category_id', models.UUIDField(db_index=True)),
                ('is_required', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='attributes.attribute')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('category_id', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('value_text', models.CharField(blank=True, default='', max_length=500)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='attributes.attribute')),
                ('attribute_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_assignments', to='attributes.attributevalue')),
            ],
            options={
                'indexes': [models.Index(fields=['product_id', 'attribute'], name='attributes__product_f105bd_idx'), models.Index(fields=['attribute', 'attribute_value'], name='attributes__attribu_7f334a_idx')],
            },
        ),
    ]
