# Generated by Django 6.0.3 on 2026-04-10 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
        ('orders', '0004_order_discount_amount_order_promotion_code_and_more'),
        ('products', '0002_product_fulfillment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='The code customers type at checkout (case-insensitive on lookup).', max_length=64, unique=True)),
                ('name', models.CharField(help_text="Internal label for the admin (e.g. 'First-order welcome 10%').", max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Internal notes — never shown to customers.')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('free_shipping', 'Free shipping')], default='percent', max_length=20)),
                ('discount_value', models.PositiveIntegerField(default=0, help_text="For 'percent': 1-100. For 'free_shipping': ignored.")),
                ('scope', models.CharField(choices=[('all', 'Whole cart'), ('category', 'Specific categories'), ('brand', 'Specific brands'), ('product', 'Specific products')], default='all', max_length=20)),
                ('min_subtotal', models.PositiveIntegerField(default=0, help_text='Minimum cart subtotal (in pence) required to apply this code.')),
                ('is_first_order_only', models.BooleanField(default=False, help_text='If True, customer must have zero prior non-cancelled orders.')),
                ('is_one_per_customer', models.BooleanField(default=False, help_text='If True, each user/email may only redeem this code once.')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses_total', models.PositiveIntegerField(blank=True, help_text='Optional global cap on total redemptions.', null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(blank=True, help_text='Optional cap per individual user/email.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Cached counter — incremented atomically on redemption.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source', models.CharField(choices=[('newsletter', 'Newsletter signup'), ('influencer', 'Influencer / partner'), ('manual', 'Manual / one-off'), ('campaign', 'Marketing campaign'), ('referral', 'Customer referral')], db_index=True, default='manual', max_length=20)),
                ('campaign_label', models.CharField(blank=True, default='', help_text="Free-form label for grouping (e.g. 'instagram_oct_2026').", max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to=settings.AUTH_USER_MODEL)),
                ('scope_brands', models.ManyToManyField(blank=True, related_name='promotions', to='brands.brand')),
                ('scope_categories', models.ManyToManyField(blank=True, related_name='promotions', to='categories.category')),
                ('scope_products', models.ManyToManyField(blank=True, related_name='promotions', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_email', models.EmailField(blank=True, default='', help_text='Snapshot of the email used (for guest checkouts).', max_length=254)),
                ('discount_amount', models.PositiveIntegerField(help_text='Actual discount amount applied to the order, in pence.')),
                ('subtotal_at_use', models.PositiveIntegerField(help_text='Cart subtotal at the moment of redemption, in pence.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_redemptions', to='orders.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.promotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['source', 'is_active'], name='promotions__source_73d9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['starts_at', 'ends_at'], name='promotions__starts__1b26a0_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['promotion', 'created_at'], name='promotions__promoti_983669_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['user'], name='promotions__user_id_c6edaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotionredemption',
            constraint=models.UniqueConstraint(fields=('promotion', 'order'), name='uniq_promotion_per_order'),
        ),
    ]
