# Generated by Django 6.0.3 on 2026-04-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='click_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached counter — incremented when the apply URL (?promo=CODE) is opened in a browser.'),
        ),
    ]
